version: '3.8'
services:
  database:
    image: microsoft/mssql-server-linux:2017-latest
    container_name: mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourSTRONG!Passw0rd
    ports:
      - '1401:1433'
    volumes:
      - bank:/var/opt/mssql
  app:
    container_name: nwba-app
    build: ./NWBA_Web_Application
    environment:
      - ConnectionStrings:NWBAConnectionString=Server=mssql;Database=Bank;User=SA;Password=YourSTRONG!Passw0rd
      - ASPNETCORE_ENVIRONMENT=”development”
    ports:
      - '8080:80'
    depends_on:
      - "database"
    restart: on-failure
  api:
    container_name: nwba-api
    build: ./WebApi
    environment:
      - ConnectionStrings:NWBAConnectionString=Server=mssql;Database=Bank;User=SA;Password=YourSTRONG!Passw0rd
      - ASPNETCORE_ENVIRONMENT=”development”
    ports: #in case we want to access this api elsewhere, but the admin app uses the container name
      - '44343:80'
    depends_on:
      - "app"
  admin:
    container_name: nwba-admin
    build:
      context: .
      dockerfile: ./NWBA_Web_Admin/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=”development”
    ports:
      - '80:80'
    depends_on:
      - "api"
volumes:
  bank: